[versions]
androidx-arch = "2.2.0"
androidx-test = "1.6.1"
androidx-test-monitor = "1.7.1"
coroutines-test = "1.8.1"
espresso = "3.5.1"
hamcrest = "2.2"
junit = "4.13.2"
junit-test = "1.2.1"
junit5 = '5.10.1'
jraska-livedata-test = "1.2.0"
mockito = "5.4.0"
mockito-inline = "5.2.0"
mockito-kotlin = "5.4.0"
test-parameter-injector = "1.8"
truth = "1.1.3"
turbine = "1.0.0"
roboelectric = "4.11.1"
room-test = "2.6.1"
runner = "1.6.1"
coil = "2.5.0"
system-stubs-jupiter = "2.1.6"
truth-ext = "1.6.0"

[libraries]
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
arch-core-test = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch" }
compose-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-test-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-test" }
junit5-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
hamcrest = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
jraska-livedata-test = { module = "com.jraska.livedata:testing-ktx", version.ref = "jraska-livedata-test" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
test-monitor = { module = "androidx.test:monitor", version.ref = "androidx-test-monitor" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-ext = { module = "androidx.test.ext:truth", version.ref = "truth-ext" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
room-test = { module = "androidx.room:room-testing", version.ref = "room-test" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }
system-stubs-jupiter = { module = "uk.org.webcompere:system-stubs-jupiter", version.ref = "system-stubs-jupiter" }

[bundles]
unit-test = ["junit", "truth", "hamcrest", "mockito", "mockito-inline", "mockito-kotlin", "turbine"]
ui-test = ["roboelectric", "espresso", "espresso-intents"]
junit5-api = ["junit-jupiter", "junit-jupiter-api", "junit-vintage-engine", "junit-jupiter-params"]
